[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia = "https://eth-sepolia.g.alchemy.com/v2/HWmRDrA5fpsgoqzqpebGAfg3J85bo7O_", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/31rqxYUCeDqb7JaPh9BWp" }
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@ccip/=lib/ccip/',
    '@chainlink-local/=lib/chainlink-local/',
]
# '@openzeppelin/=lib/openzeppelin-contracts/',

[invariant]
# runs = 1000
# depth = 128
# fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
